### PR TITLE
Merge node

### PR DESCRIPTION
**Pull request by mykmelez**

### CODE REVIEW

**Comment by mykmelez** [comment]
The bustage here comes from the landing of the ABI-stable Node API (https://github.com/nodejs/node/pull/11975), which adds a *napi_create_symbol* function to node_api.cc that references *v8::Symbol*, which we haven't yet shimmed.

**Comment by tbsaunde** [comment]
On Tue, Apr 04, 2017 at 10:17:53AM -0700, Myk Melez wrote:
> The bustage here comes from the landing of the ABI-stable Node API (nodejs/node
> #11975), which adds a napi_create_symbol function to node_api.cc that
> references v8::Symbol, which we haven't yet shimmed.

I bet that's not too hard to implement, I'll take a look tomorrow.

Trev

**Comment by mykmelez** [comment]
> I bet that's not too hard to implement, I'll take a look tomorrow.

@tbsaunde Note this comment on line 890 of deps/spidershim/src/v8objecttemplate.cc:

```
// TODO: Handle symbols here when we implement v8::Symbol
```

**Comment by mykmelez** [comment]
I've been maintaining this PR but haven't had time to actually fix the issues, which seems unuseful, so I'm going to close this PR while keeping the branch around in case I or someone else wants to pick up this work again.

**Pull request closed without merging**
