### PR TITLE
fix compartments

### PR DESCRIPTION
**Pull request by tbsaunde**

### CODE REVIEW

**Comment by ehsan** [comment]
This PR is very weird.  Firstly it's based off of the now defunct stub branch.  Also it includes quite a few commits, not sure why.  Can you please rebase your fix as a single commit on top of the current master?  Thanks!

**Comment by tbsaunde** [comment]
On Thu, Jul 21, 2016 at 12:27:22PM -0700, Ehsan Akhgari wrote:

> This PR is very weird. Firstly it's based off of the now defunct stub branch.
> Also it includes quite a few commits, not sure why. Can you please rebase your
> fix as a single commit on top of the current master? Thanks!

because I'm dumb, all the other patches are unrelated, and I just forgot
to rebase them out before pushing.

**Comment by ehsan** [comment]
Thanks!

**Comment by ehsan** [comment]
This was not even passing our tests due to #174.  I reverted it in bbf340bf8e1c60b3c806fb68a9620e0233d41232.

**Pull request merged**
