### PR TITLE
ensure string length <= max length

### PR DESCRIPTION
**Pull request by mykmelez**
Only String::NewFromUtf8 is currently checking that the new string data's length is <= String::kMaxLength. And String::Concat doesn't check that the concatenation is within the upper bound either. All the String::New\* methods and String::Concat should have this check. This branch adds it, plus tests.

### CODE REVIEW

**Comment by mykmelez** [comment]
Hmm, StringConcatOverflow segfaults on Travis (although not locally). I'm not sure what to do about that.

**Comment by ehsan** [comment]
> Hmm, StringConcatOverflow segfaults on Travis (although not locally). I'm not sure what to do about that.

I'm not sure if I understand the test yet.  What is supposed to initialize `RandomLengthOneByteResource::string_`?  As far as I can tell this test may end up using some random memory...

**Comment by mykmelez** [comment]
> I'm not sure if I understand the test yet. What is supposed to initialize RandomLengthOneByteResource::string_? As far as I can tell this test may end up using some random memory...

I was puzzling over that too. In the original test, the memory is never initialized:

https://github.com/mozilla/spidernode/blob/master/deps/v8/test/cctest/test-api.cc#L23979-L23991

Nor is it initialized in the only other test that uses RandomLengthOneByteResource:

https://github.com/mozilla/spidernode/blob/master/deps/v8/test/cctest/test-api.cc#L727-L748

I suspect the idea is that it doesn't need to be initialized, because neither String::NewExternalOneByte nor String::Concat actually access the buffer (since NewExternalOneByte doesn't need to access it, and Concat exits early after determining that the concatenated string would be too long).

Ah, but our implementation of String::NewExternalOneByte actually copies the data:

https://github.com/mozilla/spidernode/blob/master/deps/spidershim/src/v8string.cc#L198-L212

**Comment by ehsan** [comment]
Yeah, that should be the issue.  I expect the crash to go away once you initialize the buffer.

**Comment by mykmelez** [comment]
> Yeah, that should be the issue. I expect the crash to go away once you initialize the buffer.

Indeed, I made that change in 5b75fea, then tested it on Travis in my fork, and the crash went away there.

**Pull request merged**
